### ISSUE TITLE
Why mce still using GConf?

### ISSUE THREAD

**Issue by CODeRUS** [nemomobile/mce#239]
So, why? For security reasons?

**Comment by spiiroin** [comment]
MCE does not use gconf.

In theory mce uses "mce_gconf_xxx" abstraction for accessing settings. In practice the abstraction leaks and gconf types etc are still needed. So when gconf became a problem, an API compatible builtin-gconf module was added to mce & used optionally. Later it came the only option, so gconf is present in name only.

https://github.com/nemomobile/mce/pull/14
https://github.com/nemomobile/mce/pull/168

**Comment by CODeRUS** [comment]
ah, it's not gconf but just abstart gconf-compatible settings, okay :D
just looking into gconf settings values puzzled me a lot :D

**Comment by thp** [comment]
It could make sense to at some point do a global string replace of `mce_gconf_` to something like `mce_settings_` (or similar), from `GCONF_` to `MCE_SETTINGS_` (or so) and `GConf` to `MceSettings` (again, just an idea) so that is clear that mce manages its settings by itself now? From a quick look through the code, it doesn't seem like the constants and names are used externally, so that should not break apps using mce via D-Bus or via `mce-dev` headers?

Should we open a new "nice-to-have future TODO" issue here or reopen this and reword the title?

**Comment by CODeRUS** [comment]
Create new, no need to reopen this one :)

**Comment by spiiroin** [comment]
@thp: Yes, all of it is contained within mce. The only problem is that fixing needs global search+replace - which mean it would make rebasing work in progress stuff gets ugly -> preferrable to do it at time where no major features are in the air.

Though, making a ticket for it would work as a reminder whenever such relative calm occurs.

**Comment by thp** [comment]
Done, see https://github.com/nemomobile/mce/issues/240
